/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import models.ModelCliente;
import utilitarios.ConectaBanco;
import utilitarios.ControleCliente;
import utilitarios.ModeloTabela;

/**
 *
 * @author andreson.csilva
 */
public class Clientes extends javax.swing.JFrame {
    ModelCliente mod = new ModelCliente();
    ControleCliente control = new ControleCliente();
    ConectaBanco conn = new ConectaBanco();
    int flag = 1;

    /**
     * Creates new form Clientes
     */
    public Clientes() throws ParseException {
        initComponents();
        MaskFormatter form = new MaskFormatter("##.###.###-##");
        txtRg.setFormatterFactory(new DefaultFormatterFactory(form));
        form = new MaskFormatter("###.###.###-##");
        txtCpf.setFormatterFactory(new DefaultFormatterFactory(form));
       
        preencherCombobox();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        bpnNovo = new javax.swing.JButton();
        bpnSalvar = new javax.swing.JButton();
        BpnEditar = new javax.swing.JButton();
        BpnExcluir = new javax.swing.JButton();
        bpnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bpnAnterior = new javax.swing.JButton();
        bpnPrimeiro = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        cbBairro = new javax.swing.JComboBox<>();
        bpnUltimo = new javax.swing.JButton();
        bpnSair = new javax.swing.JButton();
        bpnBairro = new javax.swing.JButton();
        labelTel = new javax.swing.JLabel();
        cbTel = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        labelEnd = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        labelRg = new javax.swing.JLabel();
        txtRg = new javax.swing.JFormattedTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        labelCpf = new javax.swing.JLabel();
        labelCidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Cadastro de Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Código");

        labelNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNome.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Bairro:");

        bpnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        bpnNovo.setText("Novo");
        bpnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpnNovoActionPerformed(evt);
            }
        });

        bpnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SALVAR.png"))); // NOI18N
        bpnSalvar.setText("Salvar");
        bpnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpnSalvarActionPerformed(evt);
            }
        });

        BpnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ALTERAR.png"))); // NOI18N
        BpnEditar.setText("Editar");
        BpnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpnEditarActionPerformed(evt);
            }
        });

        BpnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EXCLUIR.png"))); // NOI18N
        BpnExcluir.setText("Excluir");
        BpnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpnExcluirActionPerformed(evt);
            }
        });

        bpnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CANCELAR VENDA.png"))); // NOI18N
        bpnCancelar.setText("Cancelar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sigla"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bpnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PRIMEIRO.png"))); // NOI18N
        bpnAnterior.setToolTipText("Anterior");
        bpnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpnAnteriorActionPerformed(evt);
            }
        });

        bpnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PRIMEIRO1.png"))); // NOI18N
        bpnPrimeiro.setToolTipText("Primeiro");
        bpnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpnPrimeiroActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ULTIMO.png"))); // NOI18N
        jButton8.setToolTipText("Próximo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        cbBairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bpnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ULTIMO1.png"))); // NOI18N
        bpnUltimo.setToolTipText("Último");
        bpnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpnUltimoActionPerformed(evt);
            }
        });

        bpnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SAIR.png"))); // NOI18N
        bpnSair.setText("Sair");
        bpnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpnSairActionPerformed(evt);
            }
        });

        bpnBairro.setText("jButton5");
        bpnBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpnBairroActionPerformed(evt);
            }
        });

        labelTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTel.setText("Tel:");

        cbTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton12.setText("+");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        labelEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelEnd.setText("Endereço:");

        labelRg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelRg.setText("RG:");

        labelCpf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCpf.setText("CPF:");

        labelCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCidade.setText("Cidade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelEnd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEnd))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTel)
                                    .addComponent(labelRg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbTel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton12))
                                    .addComponent(txtRg))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bpnBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(168, 168, 168))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bpnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bpnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BpnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BpnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bpnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bpnPrimeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bpnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bpnUltimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bpnSair)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome)
                    .addComponent(labelTel)
                    .addComponent(cbTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelEnd)
                        .addComponent(labelRg))
                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCpf)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(cbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bpnBairro)
                        .addComponent(labelCidade)))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bpnPrimeiro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bpnAnterior, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bpnUltimo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bpnSair, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bpnNovo)
                        .addComponent(bpnSalvar)
                        .addComponent(BpnEditar)
                        .addComponent(BpnExcluir)
                        .addComponent(bpnCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bpnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpnNovoActionPerformed
        // TODO add your handling code here:
        bpnSalvar.setEnabled(true);
        bpnCancelar.setEnabled(true);
        txtEnd.setEnabled(true);
        txtNome.setEnabled(true);
        txtCpf.setEnabled(true);
        txtRg.setEnabled(true);
        bpnNovo.setEnabled(false);
        txtEnd.setText("");
        txtEnd.setText("");
        txtNome.setText("");
    }//GEN-LAST:event_bpnNovoActionPerformed

    private void bpnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bpnSairActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Telefones frm = new Telefones();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void bpnBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpnBairroActionPerformed
        // TODO add your handling code here:
        Bairro frm = new Bairro();
        frm.setVisible(true);
    }//GEN-LAST:event_bpnBairroActionPerformed

    private void bpnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpnSalvarActionPerformed
        // TODO add your handling code here:
        if(flag==1){
            mod.setId(Integer.parseInt(txtCod.getText()));
            mod.setNome(txtNome.getText());
            mod.setEndereco(txtEnd.getText());
            mod.setRg(txtRg.getText());
            mod.setCpf(txtCpf.getText());
            mod.setBairro((String) cbBairro.getSelectedItem());
            mod.setCidade((String) labelCidade.getText());
            mod.setTelefone((String)  cbTel.getSelectedItem());
            control.Inserir(mod);
            bpnSalvar.setEnabled(!true);
            bpnCancelar.setEnabled(!true);
            txtEnd.setEnabled(!true);
            txtNome.setEnabled(!true);
            txtCpf.setEnabled(!true);
            txtRg.setEnabled(!true);
            bpnNovo.setEnabled(!false);
            txtEnd.setText("");
            txtEnd.setText("");
            txtNome.setText("");
            preencherTabela();
            
        }else{
             mod.setId(Integer.parseInt(txtCod.getText()));
            mod.setNome(txtNome.getText());
            mod.setEndereco(txtEnd.getText());
            mod.setRg(txtRg.getText());
            mod.setCpf(txtCpf.getText());
            mod.setBairro((String) cbBairro.getSelectedItem());
            mod.setCidade((String) labelCidade.getText());
            mod.setTelefone((String)  cbTel.getSelectedItem());
            control.alterar(mod);
            bpnSalvar.setEnabled(!true);
            bpnCancelar.setEnabled(!true);
            txtEnd.setEnabled(!true);
            txtNome.setEnabled(!true);
            txtCpf.setEnabled(!true);
            txtRg.setEnabled(!true);
            bpnNovo.setEnabled(!false);
            txtEnd.setText("");
            txtEnd.setText("");
            txtNome.setText("");
            flag = 1;
            preencherTabela();
            
        }
    }//GEN-LAST:event_bpnSalvarActionPerformed

    private void BpnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpnEditarActionPerformed
        // TODO add your handling code here:
        txtEnd.setEnabled(true);
        txtNome.setEnabled(true);
        txtCpf.setEnabled(true);
        txtRg.setEnabled(true);
        bpnSalvar.setEnabled(true);
        BpnEditar.setEnabled(false);
        flag = 2;
    }//GEN-LAST:event_BpnEditarActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        BpnEditar.setEnabled(true);
        BpnExcluir.setEnabled(true);
        bpnCancelar.setEnabled(true);
        bpnNovo.setEnabled(false);
        mod = control.prox();
        txtEnd.setText(mod.getEndereco());
        txtNome.setText(mod.getNome());
        txtCod.setText(String.valueOf(mod.getId()));
        txtCpf.setText(mod.getCpf());
        txtRg.setText(mod.getRg());
        cbBairro.setSelectedItem(mod.getBairro());
        labelCidade.setText(mod.getCidade());
        cbTel.setSelectedItem(mod.getTelefone());

    }//GEN-LAST:event_jButton8ActionPerformed

    private void bpnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpnAnteriorActionPerformed
        // TODO add your handling code here:
        BpnEditar.setEnabled(true);
        BpnExcluir.setEnabled(true);
        bpnCancelar.setEnabled(true);
        bpnNovo.setEnabled(false);
        mod = control.ant();
        txtEnd.setText(mod.getEndereco());
        txtNome.setText(mod.getNome());
        txtCod.setText(String.valueOf(mod.getId()));
        txtCpf.setText(mod.getCpf());
        txtRg.setText(mod.getRg());
        cbBairro.setSelectedItem(mod.getBairro());
        labelCidade.setText(mod.getCidade());
        cbTel.setSelectedItem(mod.getTelefone());

    }//GEN-LAST:event_bpnAnteriorActionPerformed

    private void bpnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpnUltimoActionPerformed
        // TODO add your handling code here:
        BpnEditar.setEnabled(true);
        BpnExcluir.setEnabled(true);
        bpnCancelar.setEnabled(true);
        bpnNovo.setEnabled(false);
        mod = control.ult();
        txtEnd.setText(mod.getEndereco());
        txtNome.setText(mod.getNome());
        txtCod.setText(String.valueOf(mod.getId()));
        txtCpf.setText(mod.getCpf());
        txtRg.setText(mod.getRg());
        cbBairro.setSelectedItem(mod.getBairro());
        labelCidade.setText(mod.getCidade());
        cbTel.setSelectedItem(mod.getTelefone());

    }//GEN-LAST:event_bpnUltimoActionPerformed

    private void bpnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpnPrimeiroActionPerformed
        // TODO add your handling code here:
        BpnEditar.setEnabled(true);
        BpnExcluir.setEnabled(true);
        bpnCancelar.setEnabled(true);
        bpnNovo.setEnabled(false);
        mod = control.primeiro();
        txtEnd.setText(mod.getEndereco());
        txtNome.setText(mod.getNome());
        txtCod.setText(String.valueOf(mod.getId()));
        txtCpf.setText(mod.getCpf());
        txtRg.setText(mod.getRg());
        cbBairro.setSelectedItem(mod.getBairro());
        labelCidade.setText(mod.getCidade());
        cbTel.setSelectedItem(mod.getTelefone());

    }//GEN-LAST:event_bpnPrimeiroActionPerformed

    private void BpnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpnExcluirActionPerformed
        // TODO add your handling code here:
        mod.setId(Integer.parseInt(txtCod.getText()));
        mod.setNome(txtNome.getText());
        mod.setEndereco(txtEnd.getText());
        mod.setRg(txtRg.getText());
        mod.setCpf(txtCpf.getText());
        mod.setBairro((String) cbBairro.getSelectedItem());
        mod.setCidade((String) labelCidade.getText());
        mod.setTelefone((String) cbTel.getSelectedItem());
        control.excluir(mod);
        bpnSalvar.setEnabled(!true);
        bpnCancelar.setEnabled(!true);
        txtEnd.setEnabled(!true);
        txtNome.setEnabled(!true);
        txtCpf.setEnabled(!true);
        txtRg.setEnabled(!true);
        bpnNovo.setEnabled(!false);
        txtEnd.setText("");
        txtEnd.setText("");
        txtNome.setText("");
        preencherTabela();

    }//GEN-LAST:event_BpnExcluirActionPerformed
    public void preencherTabela(){
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"Cliente", "Endereço", "Telefone", "Cidade"};
        conn.conexao();
        conn.executaSQL("select * from clientes inner join itens_cli_tel on clientes.id_cliente = itens_cli_tel.id_cliente inner join telefone on itens_cli_tel.id_tel = telefone.id_telefone inner join bairro on clientes.id_bairro = bairro.id_bairro inner join cidade on bairro.id_cidade = cidade.id_cidade");
        try{
            conn.rs.first();
            do{
                dados.add(new Object[]{conn.rs.getString("nome_cliente"), conn.rs.getString("endereco_cliente"), conn.rs.getString("numero_tel"),conn.rs.getString("nome_cidades")});
            }while(conn.rs.next());
        }catch(SQLException ex){
            
        }
       ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTable1.setModel(modelo);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(115);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(115);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
        
    }


      public void preencherCombobox(){
      cbBairro.removeAllItems();
      
      cbTel.removeAllItems();
      conn.conexao();
      conn.executaSQL("select * from bairro order by nome_bairro");
      try{
          conn.rs.first();
          do{
              cbBairro.addItem(conn.rs.getString("nome_bairro"));
          }while(conn.rs.next());
          
          conn.executaSQL("select * from telefone order by numero_tel");
          conn.rs.first();
          do{
              cbTel.addItem(conn.rs.getString("nomero_tel"));
          }while(conn.rs.next());
      }catch (SQLException ex){
          
      }
      conn.desconecta();
  }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Clientes().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BpnEditar;
    private javax.swing.JButton BpnExcluir;
    private javax.swing.JButton bpnAnterior;
    private javax.swing.JButton bpnBairro;
    private javax.swing.JButton bpnCancelar;
    private javax.swing.JButton bpnNovo;
    private javax.swing.JButton bpnPrimeiro;
    private javax.swing.JButton bpnSair;
    private javax.swing.JButton bpnSalvar;
    private javax.swing.JButton bpnUltimo;
    private javax.swing.JComboBox<String> cbBairro;
    private javax.swing.JComboBox<String> cbTel;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelEnd;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRg;
    private javax.swing.JLabel labelTel;
    private javax.swing.JTextField txtCod;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    // End of variables declaration//GEN-END:variables
}
